graphqlQuery: "query accountByIds {
    accountByIds(id: [129583, 23980]) {
      accountId
      primarySystem {
        code
      }
      code
      longName
      shortName
      briefName
      accountStatusType {
        code
        name
      }
      accountType {
        code
      }
      startDate
      endDate
      fundingEvent {
        intendedFundingDate
        date
      }
      managementResponsibilityCenter {
        code
        name
      }
      investmentSubVehicle {
        code
        investmentVehicle {
          code
        }
      }
      profitabilityChannel {
        code
        name
      }
    }
  }"

